### ISSUE TITLE
How to modify the configure file to make it coresponding to scenarios mentioned in the paper?

### ISSUE THREAD

**Issue by fmxFranky** [oxwhirl/smacv2#12]
Hi, the paper has mentioned 15 scenarios for smacv2, and how to reimplement these scenarios by modifyinng the proposed yaml?
Thanks a lot~

**Comment by benellis3** [comment]
Hi. Thanks very much for raising an issue!

You only need to change the `n_units` and `n_enemies` entries of those configs. In my experiments I always passed those in as a command line flag. Here are the correct settings:

|      Scenario      | `n_units`  | `n_enemies` |
|--------------------|------------|-------------|
| `protoss_5_vs_5`   |          5 |           5 |
| `zerg_5_vs_5`      |          5 |           5 |
| `terran_5_vs_5`    |          5 |           5 |
| `protoss_10_vs_10` |         10 |          10 |
| `zerg_10_vs_10`    |         10 |          10 |
| `terran_10_vs_10`  |         10 |          10 |
| `protoss_20_vs_20` |         20 |          20 |
| `zerg_20_vs_20`    |         20 |          20 |
| `terran_20_vs_20`  |         20 |          20 |
| `protoss_10_vs_11` |         10 |          11 |
| `zerg_10_vs_11`    |         10 |          11 |
| `terran_10_vs_11`  |         10 |          11 |
| `protoss_20_vs_23` |         20 |          23 |
| `zerg_20_vs_23`    |         20 |          23 |
| `terran_20_vs_23`  |         20 |          23 |

In general, the first number in the scenario name is the number of allied units (`n_units`) and the second is the number of enemies (`n_enemies`). I've updated the README to make this clearer.

Please let me know if you have some more issues with setup -- I'd like to make it as clear as possible for new people.

**Comment by fmxFranky** [comment]
Thanks very much for your reply. Another question is that should i override the keys `exception_unit_types`, `unit_types`, and `weights` in the config when changing different races, i.e. protoss, zerg and terran. I found that these keys are different in your provided example yamls. And protoss have no `exception_unit_types` in `smacv2/examples/configs/sc2_gen_protoss.yaml`, i don't know whether it will occur issues.

**Comment by benellis3** [comment]
No -- you don't need to touch any settings apart from `n_units` and `n_enemies`. Obviously for the protoss scenarios, use the `sc2_gen_protoss.yaml` config file and for the `zerg` ones use the `sc2_gen_zerg.yaml` etc.

Protoss have no `exception_unit_types` because a full team of any of the protoss units is not a problem. In terran for example, a full team of medivacs would not be a valid scenario. In zerg, a full scenario of banelings can lead to strange 
behaviour because of their suicidal nature. That flag stops degenerate full teams of specific units from spawning. In protoss a full scenario of any of the units is fine.

**Comment by fmxFranky** [comment]
My marl codebase is not pymarl so that i am trying to merge these yamls into my codebase. I found that the differences between three races and 15 scenarios is `n_units`, `n_enemies` , and what i mentioned above. Now i use the following code to do this
```python
from envs.smacv2.wrapper import StarCraftCapabilityEnvWrapper
configs = all_args.map_name.split("_") # e.g. protoss_10_vs_10
race = configs[0]
n_units = int(configs[1])
n_enemies = int(configs[3])
if race == "zerg":
    unit_types = ["zergling", "baneling", "hydralisk"]
    weights = [0.45, 0.1, 0.45]
    exception_unit_types = ["baneling"]
elif race == "terran":
    unit_types = ["marine", "marauder", "medivac"]
    weights = [0.45, 0.45, 0.1]
    exception_unit_types = ["medivac"]
elif race == "protoss":
    unit_types = ["stalker", "zealot", "colossus"]
    weights = [0.45, 0.45, 0.1]
    exception_unit_types = []
distribution_config = {
    "n_units": n_units,
    "n_enemies": n_enemies,
    "team_gen": {
        "dist_type": "weighted_teams",
        "unit_types": unit_types,
        "exception_unit_types": exception_unit_types,
        "weights": weights,
        "observe": True,
    },
    "start_positions": {
        "dist_type": "surrounded_and_reflect",
        "p": 0.5,
        "map_x": 32,
        "map_y": 32,
    },
}
env = StarCraftCapabilityEnvWrapper(
    capability_config=distribution_config,
    map_name=f"10gen_{race}",
    debug=True,
    conic_fov=False,
    obs_own_pos=True,
    use_unit_ranges=True,
    min_attack_range=2,
)
```
Is there some errors in my code?

**Comment by benellis3** [comment]
I *think* that looks okay at a glance, but I think an easier approach would be to load the yamls using pyyaml to a `dict` object and then pass them to the constructor as `**env_args`. 

You probably don't want to set `debug=True` in general.

**Comment by fmxFranky** [comment]
Thank you very much, i will have a try on it.
