### ISSUE TITLE
32x32_flat.SC2Map does not exist in the original smac maps

### ISSUE THREAD

**Issue by renos** [oxwhirl/smacv2#13]
I downloaded the original smac maps and 32x32_flat.SC2Map is not included among them. Where can I find it?

**Comment by benellis3** [comment]
Hi -- I'm sorry for the slow reply. The map you are looking for is included in the repo here: https://github.com/oxwhirl/smacv2/tree/main/smacv2/env/starcraft2/maps/SMAC_Maps

I hope you managed to find it. I'm going to zip the maps folder and include it as a release so people can find the right map more easily.
