### ISSUE TITLE
How to generate different micro-maps files such as 20m.SC2Map which can be used in smac?

### ISSUE THREAD

**Issue by Monarchlee** [oxwhirl/smacv2#16]
I want to save the map files of different n_units and unit_types so that I can eval my model on these maps. How can I generate plenty of .SC2Map files with smacv2?

**Comment by benellis3** [comment]
Hi. All scenarios in SMACv2, including those of different number of enemies and unit types, happen with the same map file. You can change the number of units by adjusting the `n_units` and `n_enemies` sections of the yaml file. You can also adjust unit types, but bear in mind we do not support ones other than those listed in the yamls you can find here: https://github.com/oxwhirl/smacv2/tree/main/smacv2/examples/configs

If you want to recreate 20m, you can do that by specifying only marines in the terran yaml file and setting the number of enemies and units to be 20. You can also set `use_unit_ranges=False` to recover the SMACv1 behaviour of only using a fixed sight and attack range on all unit types if you want that..

If you want to continuously evaluate on different scenarios to the one you are training on then the easiest way of doing that is to create a bunch of different environments with different configurations up-front, and then evaluate on those.

I'm not quite sure exactly what you are trying to do, so it's hard for me to offer you more specific advice. Happy to help though!

**Comment by Monarchlee** [comment]
> 

Thanks for your help and patience. I'm just trying to eval my pre-trained models on plenty of maps with different numbers of entities and types. Doing so lets me judge if my model is general enough to smac. Now I know that maybe I can just load my model and eval it with different configs. My original plan is to create various SC2Map files so that I can test my model on them. Thanks again.

**Comment by benellis3** [comment]
Yup that makes sense. Let me know if you need any more help.

**Comment by benellis3** [comment]
Closing, but re-open/open a new issue if you need more help
