### ISSUE TITLE
Set trained model as opponent?

### ISSUE THREAD

**Issue by linshi9658** [oxwhirl/smacv2#20]
Hello,

Based on the state-of-the-art algorithm, the reality is that the winning rate is close to 1 in many maps. Is the author interested in further expanding the function of SMAC to realize the battle between two models obtained by different algorithms? I think this can break through the upper limit of the difficulty of SC2's built-in computer, so as to keep SMAC alive forever.

**Comment by benellis3** [comment]
Hi. This isn't in our plans at the moment as it requires some reasonable engineering work, but I'd be very happy to see such a setting in the future 😄 .

**Comment by benellis3** [comment]
Closing but please reopen if you have more issues.
