### ISSUE TITLE
[Bug] Rendering in capability wrapper unusable

### ISSUE THREAD

**Issue by matteobettini** [oxwhirl/smacv2#33]
In the capability wrapper
https://github.com/oxwhirl/smacv2/blob/c911609aa02dcd8d922869757c47301f3ba1b0df/smacv2/env/starcraft2/wrapper.py#L81

The rendering function does not take the `mode` argument and thus we cannot render in rgb_arrays environments that are using the capability config

**Comment by benellis3** [comment]
Thanks very much for reporting this -- I've fixed it now I believe. Let me know if you have more issues.
