### ISSUE TITLE
[Bug] AttributeError about 'state_feature_names' in starcraft.py

### ISSUE THREAD

**Issue by stranger117** [oxwhirl/smacv2#35]
When I try to use 'python -m smacv2.examples.random_agents' to test smacv2, it says 'StarCraft2Env' object has no attribute 'state_feature_names'.

![Screenshot from 2023-10-17 17-47-45](https://github.com/oxwhirl/smacv2/assets/84925671/4b256d21-2821-4389-a6e4-2a9617485123)

**Comment by duanyiqun** [comment]
Same here, anyone have any idea to solve this?

**Comment by RupaliBhati** [comment]
I uncommented line 417 `self.state_feature_names = self.build_state_feature_names()` and that got rid of the error. Not sure if that changes the logic of the file though.

**Comment by benellis3** [comment]
Closing -- feel free to reopen if you have more issues

**Comment by benellis3** [comment]
Closing but please reopen if you have more issues
