### ISSUE TITLE
How to set the WANDB_API_KEY_FILE environment variable 

### ISSUE THREAD

**Issue by RupaliBhati** [oxwhirl/smacv2#36]
In [smacv2](https://github.com/oxwhirl/smacv2/tree/main)
/RUNNING_EXPERIMENTS.md step 0 is to set the WANDB_API_KEY_FILE environment variable as mentioned in the introduction. However, in the Introduction, there is some missing text on how to do this. Could you please help me set that up?

Thanks!

**Comment by benellis3** [comment]
Hi. Apologies looks like I missed out some instructions. I've updated the doc now. Let me know if you have further issues!

**Comment by RupaliBhati** [comment]
Thanks @benellis3 !
