### ISSUE TITLE
How to disable specific properties?

### ISSUE THREAD

**Issue by kinalmehta** [oxwhirl/smacv2#5]
Hi,

I see the 4 main contributions of SMACv2 are as follows
- random team compositions
- random start positions
- conic fov
- conic attack/shoot

I want to disable follows
- random team compositions (only increase stochasticity by start positions)
- conic fov (attack should follow conic constraints, but fov should be like SMACv1)

This would help reproduce the paper's ablation studies.
I'm unable to configure the above described behaviour. Could you please direct me to the relevant reference? It'll be great if there is an example of this.

Thanks
Kinal

**Comment by kinalmehta** [comment]
Thank you @benellis3 
This answers most part my queries. 

So based on my understanding, I believe having multiple unit types with deterministic team composition is not possible.

**Comment by benellis3** [comment]
Yeah you can use the "fixed" distribution type I believe (https://github.com/oxwhirl/smacv2/blob/main/smac/env/starcraft2/distributions.py#L33). Then you can list the team that you want. 

This isn't the most well tested use case but it should work just fine.
